# Generated by Django 4.0.6 on 2022-09-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('fabricacion', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio_fabricacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aviones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bmw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('fabricacion', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio_fabricacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Camiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ferrari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('fabricacion', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio_fabricacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lambo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('fabricacion', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio_fabricacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mercedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('fabricacion', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio_fabricacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('fabricacion', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio_fabricacion', models.IntegerField()),
            ],
        ),
    ]
