# Generated by Django 4.0.6 on 2022-09-17 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audi',
        ),
        migrations.DeleteModel(
            name='Bmw',
        ),
        migrations.DeleteModel(
            name='Ferrari',
        ),
        migrations.DeleteModel(
            name='Lambo',
        ),
        migrations.DeleteModel(
            name='Mercedes',
        ),
        migrations.DeleteModel(
            name='Vw',
        ),
    ]
