# Generated by Django 4.0.6 on 2022-09-17 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0002_delete_audi_delete_bmw_delete_ferrari_delete_lambo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autos',
            old_name='tipo',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='aviones',
            old_name='marca',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='camiones',
            old_name='tipo',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='motos',
            old_name='tipo',
            new_name='modelo',
        ),
        migrations.RemoveField(
            model_name='aviones',
            name='tipo',
        ),
    ]
