# Generated by Django 4.0.6 on 2022-09-18 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0003_rename_tipo_autos_modelo_rename_marca_aviones_modelo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autos',
            old_name='anio',
            new_name='año',
        ),
    ]
