# Generated by Django 4.0.6 on 2022-09-18 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0004_rename_anio_autos_año'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aviones',
            old_name='anio',
            new_name='año',
        ),
        migrations.RenameField(
            model_name='camiones',
            old_name='anio',
            new_name='año',
        ),
        migrations.RenameField(
            model_name='motos',
            old_name='anio',
            new_name='año',
        ),
    ]
