# Generated by Django 4.0.6 on 2022-09-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0008_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.AddField(
            model_name='aviones',
            name='marca',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
