# Generated by Django 4.0.6 on 2022-09-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0009_delete_imagen_aviones_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviones',
            name='marca',
        ),
    ]
