# Generated by Django 4.0.6 on 2022-10-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0011_category_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canalmensaje',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='canalmensaje',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='canalusuario',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='canalusuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Canal',
        ),
        migrations.DeleteModel(
            name='CanalMensaje',
        ),
        migrations.DeleteModel(
            name='CanalUsuario',
        ),
    ]
