# Generated by Django 4.0.6 on 2022-10-12 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='usuarios',
            field=models.ManyToManyField(blank=True, through='Dm.CanalUsuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='canalmensaje',
            name='canal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dm.canal'),
        ),
        migrations.AlterField(
            model_name='canalusuario',
            name='canal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dm.canal'),
        ),
    ]
